services:   
  build:
    image: linorobot2:${BASE_IMAGE}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - ROS_DISTRO=${ROS_DISTRO:-jazzy}
        - HOST_ARCH=${HOST_ARCH:-amd64}
        - ROBOT_BASE=${ROBOT_BASE}
        - LASER_SENSOR=${LASER_SENSOR}
        - DEPTH_SENSOR=${DEPTH_SENSOR}
        - VIRTUALGL_ENABLED=${VIRTUALGL_ENABLED:-true}
        - VIRTUALGL_VER=${VIRTUALGL_VER:-3.1}
      target: final

  base:
    image: linorobot2:${BASE_IMAGE}
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - GPU_ID=${GPU_ID:-0}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - LINOROBOT2_BASE=${ROBOT_BASE} 
      - LINOROBOT2_LASER_SENSOR=${LASER_SENSOR} 
      - LINOROBOT2_DEPTH_SENSOR=${DEPTH_SENSOR} 
      - DISPLAY=${DISPLAY} 
      - QT_X11_NO_MITSHM=1
      - WORLD=${WORLD:-playground}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/ros/.Xauthority
      - ../linorobot2_navigation/maps:/home/ros/linorobot2_ws/src/linorobot2/linorobot2_navigation/maps:rw)


  gazebo:
    container_name: gazebo
    extends: base
    environment:
      - IGN_IP=127.0.0.1
      - GZ_IP=127.0.0.1
    command: > 
      ros2 launch linorobot2_gazebo gazebo.launch.py 
      spawn_y:=${SPAWN_Y:-0.0}
      spawn_yaw:=${SPAWN_Z:-0.0}
    devices:
      - /dev:/dev
    volumes:
      - ../linorobot2_gazebo/worlds:/home/ros/linorobot2_ws/src/linorobot2/linorobot2_gazebo/worlds:rw)
      - ../linorobot2_gazebo/models:/home/ros/linorobot2_ws/src/linorobot2/linorobot2_gazebo/models:rw)

  dev:
    container_name: dev
    extends: base
    command: sleep infinity
    volumes:
    - ../.:/home/ros/linorobot2_ws/src/linorobot2

  bringup:
    container_name: bringup
    extends: base
    command: >
      ros2 launch linorobot2_bringup bringup.launch.py 
      custom_robot:=${CUSTOM_ROBOT}
      extra:=${LAUNCH_EXTRA} 
      odom_topic:=${ODOM_TOPIC}
      base_serial_port:=${BASE_SERIAL_PORT}
      joy:=${LAUNCH_JOYSTICK}
    # devices:
    #   - /dev/ldlidar:/dev/ldlidar # This is needed for all hardware to be connected

  slam:
    container_name: slam
    extends: base
    command: >
      ros2 launch linorobot2_navigation slam.launch.py
      rviz:=${RVIZ:-false}
      sim:=${SIM:-false}

  navigate:
    container_name: navigate
    extends: base
    command: >
      ros2 launch linorobot2_navigation navigation.launch.py
      map:=/home/ros/linorobot2_ws/src/linorobot2/linorobot2_navigation/maps/${WORLD:-turtlebot3_world}.yaml
      rviz:=${RVIZ:-false}
      sim:=${SIM:-false}

  save-map:
    container_name: save-map
    extends: base
    command: >
      ros2 run nav2_map_server map_saver_cli 
      -f /home/ros/linorobot2_ws/src/linorobot2/linorobot2_navigation/maps/map
      --fmt png
      --ros-args -p save_map_timeout:=10000.

  rviz-nav:
    container_name: rviz-nav
    extends: base
    command: rviz2 -d /home/ros/linorobot2_ws/src/linorobot2/linorobot2_navigation/rviz/linorobot2_navigation.rviz

  rviz:
    container_name: rviz
    extends: base
    command: rviz2

  webtop:
    container_name: webtop
    image: lscr.io/linuxserver/webtop:latest
    environment:
    - DISPLAY=:200
    network_mode: host
    devices:
    - /dev/dri:/dev/dri 

  kasmvnc:
    container_name: kasmvnc
    image: lsiobase/kasmvnc:alpine321
    environment:
    - DISPLAY=:200
    network_mode: host
    devices:
    - /dev/dri:/dev/dri
