name: colcon build
on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ jazzy ] # Adjust this if your default branch is different
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        base_image: [hardware, gazebo, gazebo-cuda]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install and Build ROS2 environment - ${{ matrix.base_image }}
        run: |
          export ROS_DISTRO=jazzy
          export BASE_IMAGE=${{ matrix.base_image }}
          cd docker && docker compose build
        shell: bash
